### PR TITLE
1807 wrong icon fixed

### LINKED ISSUE #1807: 11.1 Wrong icon for Residual vs. Time plot tab
@Yuri05 commented on [Mon Nov 21 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2437)

grafik

### PR DESCRIPTION
**Pull request by georgeDaskalakis**
closes #1807

### CODE REVIEW

**Review by rwmcintosh — APPROVED** [review]

File: src/OSPSuite.Presentation/Presenters/SimulationResidualVsTimeChartPresenter.cs [hunk 1]
```diff
@@ -33,7 +33,7 @@ public class SimulationResidualVsTimeChartPresenter : SimulationVsObservedDataCh
       public SimulationResidualVsTimeChartPresenter(ISimulationVsObservedDataView view, ChartPresenterContext chartPresenterContext,
          IObservedDataRepository observedDataRepository, IResidualCalculatorFactory residualCalculatorFactory,
          IResidualsVsTimeChartService residualsVsTimeChartService)
-         : base(view, chartPresenterContext, ApplicationIcons.PredictedVsObservedAnalysis,
+         : base(view, chartPresenterContext, ApplicationIcons.ResidualVsTimeAnalysis,
```
Comment (Yuri05) [inline src/OSPSuite.Presentation/Presenters/SimulationResidualVsTimeChartPresenter.cs:36]: @georgeDaskalakis in MoBi, another presenter is used?
(just wondering because the icon in MoBi was displayed correctly before the fix)

Comment (georgeDaskalakis) [reply src/OSPSuite.Presentation/Presenters/SimulationResidualVsTimeChartPresenter.cs:36]: @Yuri05, yes in MoBi we have the fixed tabs, taht are explicitely named in code. The caption is the same one of course, coming from Core.
