### PR TITLE
#1578 error when right clicking on Grid Cell

### LINKED ISSUE #1578: Error
When opening any observed data set and performing right mouse click on the highlighted area: the error below occurs.
grafik

Application:
PK-Sim® 11.0.0

Cannot find column 2.

Stack trace:
```
at System.Data.DataColumnCollection.get_Item(Int32 index)
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.GetColumnIdFromColumnIndex(Int32 columnIndex)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryDataPresenter.columnFromColumnIndex(Int32 columnIndex)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryDataPresenter.AvailableUnitsFor(Int32 columnIndex)
   at OSPSuite.UI.Binders.UnitsMenuBinder`1.CreateMenuUnits(T identifier, DXPopupMenu menu)
   at OSPSuite.UI.Binders.GridViewColumnUnitsMenuBinder`1.onPopUpMenuShowing(PopupMenuShowingEventArgs e)
   at OSPSuite.UI.Binders.GridViewColumnUnitsMenuBinder`1.<>c__DisplayClass1_0.<.ctor>b__1()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

### PR DESCRIPTION
**Pull request by georgeDaskalakis**
closes #1578

### CODE REVIEW

File: src/OSPSuite.Presentation/Presenters/ObservedData/BaseDataRepositoryDataPresenter.cs [hunk 1]
```diff
@@ -105,6 +105,7 @@ public void Handle(ObservedDataTableChangedEvent eventToHandle)
 
       protected string GetColumnIdFromColumnIndex(int columnIndex)
       {
+         if (columnIndex >= _datatable.Columns.Count) return null;
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/ObservedData/BaseDataRepositoryDataPresenter.cs:108]: return next line

**Review by msevestre — APPROVED** [review]

File: src/OSPSuite.Presentation/Presenters/ObservedData/BaseDataRepositoryDataPresenter.cs (hunk 1 above)
Comment (georgeDaskalakis) [reply src/OSPSuite.Presentation/Presenters/ObservedData/BaseDataRepositoryDataPresenter.cs]: done
