### PR TITLE
2566 fixed

### LINKED ISSUE #2566: 12.1 Persisting chart error messages
[Crash_Sim.zip](https://github.com/user-attachments/files/21344477/Crash_Sim.zip)
Try to open the simulation **S1** from the attached project: the error below comes multiple times.

If I run the simulation, the same error comes again several times. After that, the simulated curve is plotted.

```
Application:
MoBi® 12.1.0

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.Handle(ChartUpdatedEvent chartUpdatedEvent)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

### PR DESCRIPTION
**Pull request by georgeDaskalakis**
closes #2566

### CODE REVIEW

**Review by msevestre — APPROVED** [review]

File: src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs [hunk 1]
```diff
@@ -732,6 +733,22 @@ private void invalidateErrorUnit()
...
+      {
+         if (errorColumn.Unit.SelectedUnit != null && errorColumn.Unit.SelectedUnit != UnitDescription.InvalidUnit
+                                                   && errorColumn.ErrorStdDev == null)
+            errorColumn.ErrorStdDev = Constants.STD_DEV_ARITHMETIC;
+      }
+
+      private static void checkErrorUnitAgainstMeasurementUnit(Column errorColumn, Column measurementColumn)
+      {
          if (errorColumn.ErrorStdDev != Constants.STD_DEV_GEOMETRIC &&
              ((errorColumn.Unit?.ColumnName.IsNullOrEmpty() != measurementColumn.Unit?.ColumnName.IsNullOrEmpty()) ||
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs:753]: I feel that we are missing a few helper methods here that would make those lines more readable. It feels like we are never sure if the unit is going to bet set, of it's going to be equal to something.

I am glad we have tests to that refactoring should not ber hard
