### PR TITLE
Fixes #114 export to excel should use name of curve

### LINKED ISSUE #114: Exception in ParameterIdentificationValidator
when running a PI with an output without any observed data mapped

https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/212

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/OSPSuite.Presentation/DTO/Charts/CurveDTO.cs [hunk 1]
```diff
@@ -129,13 +130,16 @@ public static IEnumerable<IBusinessRule> All
...
             {
+               yield return nameCannotBeEmpty;
                yield return dataDimensionMatchesXAxis;
                yield return dataDimensionMatchesYAxis;
                yield return dataDimensionMatchesYAxisType;
                yield return canConvertYAxisTypeToYAxisUnits;
             }
          }
 
+         private static IBusinessRule nameCannotBeEmpty { get; } = GenericRules.NonEmptyRule<CurveDTO>(x => x.Name, Error.NameIsRequired);
```
Comment (msevestre) [inline src/OSPSuite.Presentation/DTO/Charts/CurveDTO.cs]: Adding a rule that was not there before. does not hurt to be consistent

File: src/OSPSuite.Presentation/DTO/NonEmptyNameDTO.cs [hunk 2]
```diff
@@ -37,32 +37,17 @@ private static bool nameDoesNotContainerIllegalCharacters(string name)
...
-         {
-            get
-            {
-               return CreateRule.For<NonEmptyNameDTO>()
-                  .Property(item => item.Name)
-                  .WithRule((dto, name) => nameDoesNotContainerIllegalCharacters(name))
-                  .WithError(Error.NameCannotContainIllegalCharacters(Constants.ILLEGAL_CHARACTERS));
-            }
-         }
+         public static IBusinessRule NameDoesNotContainIllegalCharacters { get; } = CreateRule.For<NonEmptyNameDTO>()
```
Comment (msevestre) [inline src/OSPSuite.Presentation/DTO/NonEmptyNameDTO.cs]: Just refactoring. Nothing new

File: src/OSPSuite.Presentation/Presenters/Charts/ChartDisplayPresenter.cs [hunk 3]
```diff
@@ -317,15 +311,12 @@ public virtual void ExportToExcel()
          var visibleCurves = Chart.Curves.Where(x => x.Visible).ToList();
          if (!visibleCurves.Any()) return;
 
-         var fileName = _dialogCreator.AskForFileToSave(Captions.ExportChartToExcel, Constants.Filter.EXCEL_SAVE_FILE_FILTER, Constants.DirectoryKey.REPORT);
+         var fileName = _dialogCreator.AskForFileToSave(Captions.ExportChartToExcel, Constants.Filter.EXCEL_SAVE_FILE_FILTER, Constants.DirectoryKey.REPORT, Chart.Name);
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Charts/ChartDisplayPresenter.cs]: Added a default file name (chart.NAme... if someone took the time to give it a name, why not use it)

File: src/OSPSuite.Presentation/Presenters/Charts/ChartDisplayPresenter.cs [hunk 4]
```diff
@@ -317,15 +311,12 @@ public virtual void ExportToExcel()
...
 
-         _dataRepositoryTask.ExportToExcel(visibleCurves.Select(x => x.yData), fileName, _curveNameDefinition);
-      }
-
-      public void SetCurveNameDefinition(Func<DataColumn, string> curveNameDefinition)
-      {
-         _curveNameDefinition = curveNameDefinition;
+         var dataColumnCache = new Cache<DataColumn, Curve>(onMissingKey: x => null);
+         visibleCurves.Each(curve => dataColumnCache[curve.yData] = curve);
+         _dataRepositoryTask.ExportToExcel(dataColumnCache.Keys, fileName, col => dataColumnCache[col]?.Name ?? col.Name);
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Charts/ChartDisplayPresenter.cs]: That can be null for the xGrid

File: src/OSPSuite.Presentation/Presenters/Charts/ChartEditorAndDisplayPresenter.cs [hunk 5]
```diff
@@ -64,17 +55,6 @@ public class ChartEditorAndDisplayPresenter : AbstractCommandCollectorPresenter<
          AddSubPresenters(EditorPresenter, chartDisplayPresenter);
       }
 
-      public void SetCurveNameDefinition(Func<DataColumn, string> curveNameDefinition)
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Charts/ChartEditorAndDisplayPresenter.cs]: We do not need all of that

File: src/OSPSuite.UI/Binders/CurveBinder.cs [hunk 6]
```diff
@@ -208,7 +209,11 @@ private void refreshView()
 
       private void updateSeriesCaption()
       {
-         _series.Each(s => s.LegendText = Curve.Name);
+         var legendText = Curve.Name;
+         if (string.IsNullOrEmpty(legendText))
+            legendText = Warning.CurveNameIsMissing;
```
Comment (msevestre) [inline src/OSPSuite.UI/Binders/CurveBinder.cs]: In case the curve name was not set, show a warning (previous functionality)
