### PR TITLE
#1025 fix

### LINKED ISSUE #1025: Unhandled exception when mapping error column
Following #1024 
I removed the mapping for error by clicking on X
Then selected the ERror column again

I received
image

 See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at OSPSuite.Presentation.Presenters.Importer.MappingParameterEditorPresenter.SetErrorTypeOptions(IEnumerable`1 types, String selected)
   at OSPSuite.Presentation.Presenters.Importer.ColumnMappingPresenter.SetSubEditorSettingsForMapping(ColumnMappingDTO model)
   at OSPSuite.UI.Views.Importer.ColumnMappingView.repositoryItemPopupContainerEdit(ColumnMappingDTO model)
   at OSPSuite.DataBinding.DevExpress.RepositoryConfigurator`1.EditRepositoryFor(TypeToBind source)
   at OSPSuite.DataBinding.DevExpress.Column`2.EditRepositoryItemFor(TObjectType sourceObject)
   at OSPSuite.DataBinding.DevExpress.XtraGrid.GridViewAutoBindColumn`2.EditRepositoryItemFor(TObjectType sourceObject)
   at OSPSuite.DataBinding.DevExpress.CellProperties`1.EditRepository()
   at OSPSuite.DataBinding.DevExpress.XtraGrid.GridViewBinder`1.showCustomCellEditForEditing(Object sendter, CustomRowCellEditEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.GridView.RequestCellEditor(GridCellInfo cell)
   at DevExpress.XtraGrid.Views.Grid.GridView.ActivateInplaceEditor(GridCellInfo cell)
   at DevExpress.XtraGrid.Views.Base.BaseView.ShowEditorByMouse()
   at DevExpress.XtraGrid.Views.Grid.Handler.GridRegularRowNavigator.OnMouseDown(GridHitInfo hitInfo, DXMouseEventArgs e)
   at DevExpress.XtraGrid.Views.Grid.Handler.GridHandler.OnMouseDown(MouseEventArgs ev)
   at DevExpress.Utils.Controls.BaseHandler.ProcessEvent(EventType etype, Object args)
   at DevExpress.XtraGrid.GridControl.OnMouseDown(MouseEventArgs ev)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PKSim
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/PKSim.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Utils.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Utils.v20.1.dll
----------------------------------------
DevExpress.Data.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Data.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Data.v20.1.dll
----------------------------------------
PKSim.UI
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/PKSim.UI.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 3.1.0.0
    Win32 Version: 3.100.19.56504
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
OSPSuite.Utility
    Assembly Version: 4.0.0.4
    Win32 Version: 4.0.0.4
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Utility.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
OSPSuite.Core
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Core.DLL
----------------------------------------
DevExpress.Data.Desktop.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Data.Desktop.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Data.Desktop.v20.1.dll
----------------------------------------
PKSim.Infrastructure
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/PKSim.Infrastructure.DLL
----------------------------------------
OSPSuite.Presentation
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Presentation.DLL
----------------------------------------
PKSim.Presentation
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/PKSim.Presentation.DLL
----------------------------------------
PKSim.Assets
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/PKSim.Assets.DLL
----------------------------------------
OSPSuite.UI
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.UI.DLL
----------------------------------------
OSPSuite.Assets.Images
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Assets.Images.DLL
----------------------------------------
Northwoods.Go
    Assembly Version: 5.2.0.46
    Win32 Version: 5.2.0.46
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Northwoods.Go.DLL
----------------------------------------
OSPSuite.Infrastructure.Castle
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Infrastructure.Castle.DLL
----------------------------------------
Castle.Windsor
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.3.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Castle.Core.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PKSim.Core
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/PKSim.Core.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
OSPSuite.Infrastructure
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Infrastructure.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 3.1.0.0
    Win32 Version: 3.100.19.56504
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Microsoft.Extensions.Logging.DLL
----------------------------------------
OSPSuite.Infrastructure.Serialization
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Infrastructure.Serialization.DLL
----------------------------------------
OSPSuite.Assets
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Assets.DLL
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.0.1
    Win32 Version: 4.6.26919.02
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/System.Drawing.Common.DLL
----------------------------------------
DevExpress.RichEdit.v20.1.Core
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.RichEdit.v20.1.Core/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.RichEdit.v20.1.Core.dll
----------------------------------------
DevExpress.Office.v20.1.Core
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Office.v20.1.Core/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Office.v20.1.Core.dll
----------------------------------------
DevExpress.XtraBars.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraBars.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraBars.v20.1.dll
----------------------------------------
DevExpress.XtraEditors.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraEditors.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraEditors.v20.1.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
DevExpress.XtraRichEdit.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraRichEdit.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraRichEdit.v20.1.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
DevExpress.XtraGrid.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraGrid.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraGrid.v20.1.dll
----------------------------------------
OSPSuite.Infrastructure.Import
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Infrastructure.Import.DLL
----------------------------------------
DevExpress.XtraTreeList.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraTreeList.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraTreeList.v20.1.dll
----------------------------------------
Northwoods.Go.Layout
    Assembly Version: 5.2.0.46
    Win32 Version: 5.2.0.46
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Northwoods.Go.Layout.DLL
----------------------------------------
DevExpress.XtraPivotGrid.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraPivotGrid.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraPivotGrid.v20.1.dll
----------------------------------------
DevExpress.PivotGrid.v20.1.Core
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.PivotGrid.v20.1.Core/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.PivotGrid.v20.1.Core.dll
----------------------------------------
DevExpress.XtraCharts.v20.1.UI
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraCharts.v20.1.UI/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraCharts.v20.1.UI.dll
----------------------------------------
DevExpress.XtraCharts.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraCharts.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraCharts.v20.1.dll
----------------------------------------
DevExpress.Charts.v20.1.Core
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Charts.v20.1.Core/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Charts.v20.1.Core.dll
----------------------------------------
DevExpress.Printing.v20.1.Core
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Printing.v20.1.Core/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Printing.v20.1.Core.dll
----------------------------------------
DevExpress.XtraLayout.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraLayout.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraLayout.v20.1.dll
----------------------------------------
OSPSuite.DataBinding
    Assembly Version: 3.0.0.4
    Win32 Version: 3.0.0.4
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.DataBinding.DLL
----------------------------------------
OSPSuite.Serializer
    Assembly Version: 3.0.0.1
    Win32 Version: 3.0.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Serializer.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
OSPSuite.TeXReporting
    Assembly Version: 3.0.0.4
    Win32 Version: 3.0.0.4
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.TeXReporting.DLL
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
PKSim.Assets.Images
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/PKSim.Assets.Images.DLL
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 4.3.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Castle.Core.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
OSPSuite.FuncParser
    Assembly Version: 4.0.0.50
    Win32 Version: 4.0.0.50
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.FuncParser.DLL
----------------------------------------
OSPSuite.Infrastructure.Reporting
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Infrastructure.Reporting.DLL
----------------------------------------
NHibernate
    Assembly Version: 5.2.0.0
    Win32 Version: 5.2.5.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/NHibernate.DLL
----------------------------------------
OSPSuite.Presentation.Serialization
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Presentation.Serialization.DLL
----------------------------------------
FluentNHibernate
    Assembly Version: 2.1.2.0
    Win32 Version: 2.1.2.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/FluentNHibernate.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Newtonsoft.Json.DLL
----------------------------------------
MarkdownLog
    Assembly Version: 0.10.1.0
    Win32 Version: 0.10.1.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/MarkdownLog.DLL
----------------------------------------
OSPSuite.Infrastructure.Export
    Assembly Version: 10.0.1.0
    Win32 Version: 10.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.Infrastructure.Export.DLL
----------------------------------------
OSPSuite.DataBinding.DevExpress
    Assembly Version: 5.0.0.1
    Win32 Version: 5.0.0.1
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/OSPSuite.DataBinding.DevExpress.DLL
----------------------------------------
DevExpress.BonusSkins.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.BonusSkins.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.BonusSkins.v20.1.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.112.0
    Win32 Version: 1.0.112.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Data.Entity
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Newtonsoft.Json.Schema
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.13.24127
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Newtonsoft.Json.Schema.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
DevExpress.Pdf.v20.1.Core
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Pdf.v20.1.Core/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Pdf.v20.1.Core.dll
----------------------------------------
DevExpress.Images.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Images.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Images.v20.1.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
DevExpress.XtraPrinting.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraPrinting.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraPrinting.v20.1.dll
----------------------------------------
DevExpress.XtraCharts.v20.1.Wizard
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraCharts.v20.1.Wizard/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.XtraCharts.v20.1.Wizard.dll
----------------------------------------
DevExpress.Mvvm.v20.1
    Assembly Version: 20.1.6.0
    Win32 Version: 20.1.6.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Mvvm.v20.1/v4.0_20.1.6.0__b88d1754d700e49a/DevExpress.Mvvm.v20.1.dll
----------------------------------------
Ranorex.Libs.WinForms
    Assembly Version: 8.3.3.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Ranorex%208.3/Bin/x64/Ranorex.Libs.WinForms.dll
----------------------------------------
Ranorex.Plugin.WinFormsProxy
    Assembly Version: 8.3.3.0
    Win32 Version: 8.3.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Ranorex%208.3/Bin/x64/Ranorex.Plugin.WinFormsProxy.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Iesi.Collections
    Assembly Version: 4.0.0.4000
    Win32 Version: 4.0.4.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/Iesi.Collections.DLL
----------------------------------------
MetaDataContentProxyAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 5.2.5.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/NHibernate.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 1.3.1.9
    Win32 Version: 1.3.1.9
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/ICSharpCode.SharpZipLib.DLL
----------------------------------------
NPOI
    Assembly Version: 2.5.1.0
    Win32 Version: 2.5.1.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/NPOI.DLL
----------------------------------------
NPOI.OOXML
    Assembly Version: 2.5.1.0
    Win32 Version: 2.5.1.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/NPOI.OOXML.DLL
----------------------------------------
NPOI.OpenXml4Net
    Assembly Version: 2.5.1.0
    Win32 Version: 2.5.1.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/NPOI.OpenXml4Net.DLL
----------------------------------------
NPOI.OpenXmlFormats
    Assembly Version: 2.5.1.0
    Win32 Version: 2.5.1.0
    CodeBase: file:///C:/projects/PK-Sim/src/PKSim/bin/Debug/net472/NPOI.OpenXmlFormats.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

### PR DESCRIPTION
**Pull request by georgeDaskalakis**
closes #1025

### CODE REVIEW

File: src/OSPSuite.Presentation/Presenters/Importer/MappingParameterEditorPresenter.cs [hunk 1]
```diff
@@ -95,7 +95,7 @@ public void SetErrorTypeOptions(IEnumerable<string> types, string selected)
          _errorEditorPresenter.SetOptions(new Dictionary<string, IEnumerable<string>>() { { "", types } }, selected);
          View.ShowErrorTypes();
 
-         if ( selected.Equals(Constants.STD_DEV_GEOMETRIC))
+         if (selected!= null && selected.Equals(Constants.STD_DEV_GEOMETRIC))
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Importer/MappingParameterEditorPresenter.cs:98]: In general you can do Equals(selected,xxx). If selected is nulk, it will return false
