### PR TITLE
Fixes #2203 Instantiate a single observed data simple chart

### LINKED ISSUE #2203: Instantiate a single observed data simple chart and update that single instance each time the user selects an observed data
As implemented right now, there's a separate tab opened for each observed data in the PI and there seems to be a bug in DevExpress with how user objects are handled that leads to a sudden crash without warning. Disappearing Mobi.

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #2203

# Description
Formerly using a tab per observed data mapping. This is changed to a single presenter to show the selected observed data mapping.

With that many tabs, we were triggering a crash where too many 'User Objects' were created.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
No more tabs, but the observed data display name is used to caption
image

Clearing the display when there's no mappings. The title is more of an instruction.
image

# Questions (if appropriate):

### CODE REVIEW

**Comment by msevestre** [comment]
Oh this is good. Reviewing now lol

File: src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationOutputMappingPresenter.cs [hunk 1]
```diff
@@ -96,15 +96,12 @@ public void Refresh()
          this.DoWithinLatch(() =>
          {
             UpdateCache();
-            updateOutputMapppingList();
-            _view.BindTo(_allOutputMappingDTOs);
+            updateOutputMappingList();
          });
+         _view.BindTo(_allOutputMappingDTOs);
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationOutputMappingPresenter.cs:101]: That's interesting here. Why outside?

**Review by msevestre — APPROVED** [review]
Looksk good to me
One question reqgarding moving some code outside of the DoInLatch . Just curious

File: src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationOutputMappingPresenter.cs (hunk 1 above)
Comment (rwmcintosh) [reply src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationOutputMappingPresenter.cs:101]: ah, that's because within the BindTo the selection of mapping can change. I needed to BindTo outside the latch because the latching prevents the Select event to fire.
