### PR TITLE
Fixes #2580 export of comparison results fails

### LINKED ISSUE #2580: export of comparison results fails
I cloned a Module containing the Spatial Structure (Organism).
In the cloned Module I updated several parameters in the Organism BB and compared it to the Organism BB from the original module. The comparison worked, but when I wanted to export the comparison results to excel the export failed with:

Exception: A column named 'Organism' already belongs to this DataTable.

Stack trace:

at System.Data.DataColumnCollection.RegisterColumnName(String name, DataColumn column)
   at System.Data.DataColumnCollection.BaseAdd(DataColumn column)
   at System.Data.DataColumnCollection.AddAt(Int32 index, DataColumn column)
   at OSPSuite.Utility.Extensions.DataTableExtensions.AddColumn(DataTable dataTable, DataColumn dataColumn)
   at OSPSuite.Utility.Extensions.DataTableExtensions.AddColumn(DataTable dataTable, String columnName, Type type)
   at OSPSuite.Utility.Extensions.DataTableExtensions.AddColumn[T](DataTable dataTable, String columnName)
   at OSPSuite.Utility.Extensions.DataTableExtensions.AddColumn(DataTable dataTable, String columnName)
   at OSPSuite.Presentation.Mappers.DiffItemDTOsToDataTableMapper.MapFrom(IEnumerable`1 diffItemDTOs, String leftCaption, String rightCaption)
   at OSPSuite.Presentation.Presenters.Comparisons.ComparisonPresenter.ComparisonAsTable()
   at OSPSuite.Presentation.Presenters.Comparisons.MainComparisonPresenter.ExportToExcel()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #2580

# Description
Comparison table should indicate the module when comparing building blocks. Otherwise it's confusing which is which. This cascades into a problem when exporting because the view can handle columns with the same name, but the datatable used for export to excel cannot.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

module name added for module building blocks

image

# Questions (if appropriate):

### CODE REVIEW

File: src/OSPSuite.Presentation/Presenters/ContextMenus/ComparisonCommonContextMenuItems.cs [hunk 1]
```diff
@@ -17,6 +19,11 @@ public static IMenuBarButton CompareObjectsMenu(IReadOnlyList<IObjectBase> objec
          return CompareObjectsMenu(objectsToCompare, objectsToCompare.AllNames(), context, container);
       }
 
+      public static IMenuBarButton CompareBuildingBlocksMenu(IReadOnlyList<IBuildingBlock> buildingBlocksToCompare, IOSPSuiteExecutionContext context, IContainer container)
+      {
+         return CompareObjectsMenu(buildingBlocksToCompare, buildingBlocksToCompare.Select(x => x.DisplayName).ToList(), context, container);
+      }
```
Comment (Yuri05) [inline src/OSPSuite.Presentation/Presenters/ContextMenus/ComparisonCommonContextMenuItems.cs:25]: trying hard to understand how this change fixes the Excel export...

Comment (rwmcintosh) [reply src/OSPSuite.Presentation/Presenters/ContextMenus/ComparisonCommonContextMenuItems.cs:25]: it all comes from the context menu creation.

**Review by Yuri05 — APPROVED** [review]
