### PR TITLE
1511 error unit reset fixed

### LINKED ISSUE #1511: Importer: Adding grouping resets error unit selection
- Open [Data.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8124568/Data.xlsx) for import
- Error unit is set to "mg/l" (I would expect it to be inferred from the header, i.e., "ng/ml"... but summarizing all the expected behavior in https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1501)
- Change error unit to "ng/ml"
- "Add group by" select column "Group"
- The error unit is reset to "mg/l"!

### PR DESCRIPTION
**Pull request by georgeDaskalakis**
closes #1511

### CODE REVIEW

File: src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs [hunk 1]
```diff
@@ -125,10 +124,17 @@ public void InitializeErrorUnit()
...
 
-         if (measurementColumn != null)
+         if (measurementColumn != null && unitNotSet(errorColumn))
             errorColumn.Unit = measurementColumn.Unit;
       }
 
+      private bool unitNotSet(Column column)
+      {
+         //when unit is not set and also columnName is not set
+         return (column.Unit.SelectedUnit == "?" || column.Unit.SelectedUnit == null)
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs:134]: null first

**Review by msevestre — APPROVED** [review]
ok. just swap conditions

File: src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs (hunk 1 above)
Comment (georgeDaskalakis) [reply src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs:134]: done
