### PR TITLE
Fixes #12 format clipboard for github

### LINKED ISSUE #12: Exception view: copy to clipboard
Enclose stack trace of exceptions in the exception view into the GitHub code tags **_```_**  before copying to clipboard.
Then we will get nice formatting after pasting into GitHub issues

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/OSPSuite.Presentation/Services/ExceptionManager.cs [hunk 1]
```diff
@@ -34,11 +35,23 @@ public override void LogException(Exception ex)
...
+      {
+         var message = ex.FullMessage();
+         var stackTrace = ex.FullStackTrace();
+         _exceptionView.Display(message, stackTrace, clipboardContentFrom(message, stackTrace));
+         this.LogError(ex);
+      }
+
+      private string clipboardContentFrom(string message, string stackTrace)
+      {
+         return $"Application:\n{_productInfo}\n\n{message}\n\nStack trace:\n```\n{stackTrace}\n```";
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Services/ExceptionManager.cs]: This is the actual implementation

File: tests/OSPSuite.Core.Tests/Presentation/ExceptionManagerSpecs.cs [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+      {
+         sut.LogException(_exceptionToShow);
+      }
+
+      [Observation]
+      public void should_leverage_the_exception_view_to_display_an_error_message_containg_the_exception_message()
+      {
+         _message.ShouldBeEqualTo(_exceptionToShow.FullMessage());
+         _stackTrace.ShouldBeEqualTo(_exceptionToShow.FullStackTrace());
+         _clipboard.Contains($"```\n{_exceptionToShow.FullStackTrace()}\n```").ShouldBeTrue();
```
Comment (msevestre) [inline tests/OSPSuite.Core.Tests/Presentation/ExceptionManagerSpecs.cs]: I move that test from PKSim to core and added the new convention

**Comment by msevestre** [comment]
Please merge using "Squash and merge"
