### PR TITLE
Fixes #768 crash when loading PI

### LINKED ISSUE #768: Crash when loading a PI recreated from snapshot
Load project from snapshot and open the PI "**global Parameter Identification**".
(was the same in PK-Sim 8)
[Alfentanil.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4535209/Alfentanil.zip)

```
Application:
PK-Sim® 9.0.0

Object reference not set to an instance of an object.

Stack trace:
at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationConfidenceIntervalPresenter.CalculateConfidenceIntervalFor(ParameterIdentification parameterIdentification, ParameterIdentificationRunResult runResult)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationCovarianceAnalysisPresenter.UpdateAnalysis()
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationMatrixAnalysisPresenter`1.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject) in C:\SW-Dev\PK-Sim\branches\9.0\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 44
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationConfidenceIntervalPresenter.cs [hunk 1]
```diff
@@ -24,7 +24,7 @@ public ParameterIdentificationConfidenceIntervalPresenter(IParameterIdentificati
 
       public void CalculateConfidenceIntervalFor(ParameterIdentification parameterIdentification, ParameterIdentificationRunResult runResult)
       {
-         if (runResult.JacobianMatrix == null)
+         if (runResult?.JacobianMatrix == null)
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationConfidenceIntervalPresenter.cs:27]: @Yuri05 that was it...
