### PR TITLE
Fixes #177 - Predicted vs. Observed not working for multi-curves

### LINKED ISSUE #177: PredictedVsObserved does not work as expected with multiple outputs
Using test program:
* Start PI
* Add one output amount
* Add one output fraction
* select some parameters to optimize
* Run
* Open predicted vs observed. There is no curve. 

The problem is that the code was relying before on some stuff to happen with events and this is not happening anymore. This should not be required anyways.

The problem that I see is that we set up the chart correctly (in my case to use X as fraction) but then, a call to `_predictedVsObservedChartService.SetXAxisDimension(observationColumns, Chart);`  in `ParameterIdentificationPredictedVsObservedChartPresenter` reset the X axis to amount the chart is not ok anymore. Probably some explicit code needs to be added

### PR DESCRIPTION
**Pull request by rwmcintosh**

### CODE REVIEW

File: src/OSPSuite.Presentation/Services/ParameterIdentifications/PredictedVsObservedChartService.cs [hunk 1]
```diff
@@ -106,16 +111,24 @@ public void SetXAxisDimension(IEnumerable<DataColumn> observationColumns, Parame
...
 
       public IReadOnlyList<DataRepository> AddIdentityCurves(IEnumerable<DataColumn> observationColumns, ParameterIdentificationPredictedVsObservedChart chart)
       {
          var identityCurves = addIdentityCurves(observationColumns, chart).ToList();
-         chart.UpdateAxesVisibility();
+         UpdateAxesVisibility(chart);
          return identityCurves;
       }
 
+      public void UpdateAxesVisibility(ParameterIdentificationPredictedVsObservedChart chart)
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Services/ParameterIdentifications/PredictedVsObservedChartService.cs]: Is there a reason why you would move this concern outside of the Chart when you already have a specific chart object?

File: src/OSPSuite.Presentation/Services/ParameterIdentifications/PredictedVsObservedChartService.cs [hunk 2]
```diff
@@ -132,10 +145,32 @@ private IEnumerable<DataRepository> addIdentityCurves(IEnumerable<DataColumn> ob
...
+      private IDimension mostFrequentDimension(IReadOnlyList<DataColumn> columns)
+      {
+         var preferredDimension = mostFrequentDimensionFrom(columns.Where(isPreferredDimension).Select(mergedDimensionsFor));
+
+         if (preferredDimension != null)
+            return preferredDimension;
+
+         var dimensions = columns.Select(mergedDimensionsFor).ToList();
+
+         var firstGrouping = mostFrequentDimensionFrom(dimensions);
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Services/ParameterIdentifications/PredictedVsObservedChartService.cs]: return right away
