### PR TITLE
Fixes #2601 Error when selecting "Link Data To Simulations"

### LINKED ISSUE #2601: Error when selecting "Link Data To Simulations"
[Cimetidine-Model_minimal.zip](https://github.com/user-attachments/files/21968163/Cimetidine-Model_minimal.zip)

This project was created by loading the [Cimetidine snapshot](https://github.com/Open-Systems-Pharmacology/Cimetidine-Model) and deleting all simulations but one.

1. Open the one simulation in the project: "iv 100 mg (5 min), Grahnen 1979, n=3"
2. Open the chart "iv 100 mg (5 min), Grahnen 1979, n=3" and select "Link Data to Simulations":

Image

boom:

**Application:
PK-Sim® 12.1.179

Sequence contains no matching element

Stack trace:
```
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.Core.Domain.UnitSystem.Dimension.Unit(String name)
   at OSPSuite.UI.Binders.CurveBinder.get_LLOQ()
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.IsPointBelowLLOQ(Double[] values, String seriesId)
   at OSPSuite.UI.Views.Charts.ChartDisplayView.drawSeriesPoint(CustomDrawSeriesPointEventArgs e)
   at OSPSuite.UI.Views.Charts.ChartDisplayView.<>c__DisplayClass22_4.<InitializeResources>b__15()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```**

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #2601

# Description
Some order and selection issues when we are trying to update `Used` state for a linked observation column as we select/deselect the matching calculation column.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

**Comment by rwmcintosh** [comment]
@benjaperez1983 can you revert the changes you pushed to this branch and create a new PR for the color changes

File: src/OSPSuite.Presentation/Extensions/CurveChartExtensions.cs [hunk 1]
```diff
@@ -28,10 +28,14 @@ public static Color SelectNewColor(this CurveChart chart)
          return colors[newIndex];
       }
 
-      public static void UpdateCurveColorAndStyle(this CurveChart chart, Curve curve, DataColumn dataColumn, IReadOnlyCollection<DataColumn> dataColumns)
+      public static void UpdateCurveColorAndStyle(this CurveChart chart, Curve curve, DataColumn dataColumn, IReadOnlyCollection<DataColumn> dataColumns, bool isLinkedDataToSimulation = false)
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Extensions/CurveChartExtensions.cs:31]: I don't understand what this flags mean. CAn you eplain "isLinkedDataToSimulation"?

File: src/OSPSuite.Presentation/Extensions/CurveChartExtensions.cs [hunk 2]
```diff
@@ -28,10 +28,14 @@ public static Color SelectNewColor(this CurveChart chart)
...
       {
          // Finds color from a related column
-         if (dataColumnContainsRelatedColumns(dataColumn))
+
+         if (isLinkedDataToSimulation)
+            curve.Color = chart.Curves.FirstOrDefault()?.Color ?? chart.SelectNewColor();
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Extensions/CurveChartExtensions.cs:36]: why first or default>? should not that be the color of the linked sthg, whatever this something is

File: src/OSPSuite.Presentation/Presenters/Charts/DataBrowserPresenter.cs [hunk 3]
```diff
@@ -272,14 +274,14 @@ private void updateUsedStateForColumns(IReadOnlyList<DataColumnDTO> dataColumnDT
          dataColumnDTOs.Each(dto => dto.Used = used);
       }
 
-      private void raiseUsedChanged(IReadOnlyList<DataColumn> dataColumns, bool used)
+      private void raiseUsedChanged(IReadOnlyList<DataColumn> dataColumns, bool used, bool isLinkedDataToSimulations = false)
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Charts/DataBrowserPresenter.cs:277]: I don't understand why this parameter, wherevever it's defined, is always optional. in private method, it should not be. Entry point fine, but after this, this is not easier to read
I Woudl argue that this should never be optional but I am not sure

**Review by msevestre — CHANGES_REQUESTED** [review]
Unclear to me where the code fixes the issusue 2601. There is lots of noise around setting colors etc but the actual "Sequence" not found is not seen at first glance
Naming is hard..`isLinkedDataToSimulation` remains a mystery. 
Does it mean that oberved data is llink to simuatlion results?

**Review by msevestre — APPROVED** [review]
