### PR TITLE
#2286 double click does not open PI

### LINKED ISSUE #2286: Double click does not open PI
When you double click a PI, the PI runs instead of opening.

Also, double clicking again throws an exception (because it's already running).

This must be something with the context menu.

Check for Sensitivity Analsysis too...

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #2286

# Description

Double click is triggering first menu which is "Run", changed it to "Edit"

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

image

# Questions (if appropriate):

### CODE REVIEW

**Review by rwmcintosh — APPROVED** [review]

File: src/OSPSuite.Presentation/Presenters/ContextMenus/ParameterIdentificationContextMenuItems.cs [hunk 1]
```diff
@@ -85,10 +85,11 @@ public static IMenuBarItem RunParameterIdentification(ParameterIdentification pa
 
       public static IEnumerable<IMenuBarItem> ContextMenuItemsFor(ParameterIdentification parameterIdentification, IContainer container)
       {
-         yield return RunParameterIdentification(parameterIdentification, container);
+         yield return EditParameterIdentification(parameterIdentification, container);
+            
 
-         yield return EditParameterIdentification(parameterIdentification, container)
-            .AsGroupStarter();
+         yield return RunParameterIdentification(parameterIdentification, container)
```
Comment (Yuri05) [inline src/OSPSuite.Presentation/Presenters/ContextMenus/ParameterIdentificationContextMenuItems.cs:91]: so double click just automatically executes the command behind the **first subnode**?
weird.

**Review by Yuri05 — APPROVED** [review]

File: src/OSPSuite.Presentation/Presenters/ContextMenus/ParameterIdentificationContextMenuItems.cs (hunk 1 above)
Comment (rwmcintosh) [reply src/OSPSuite.Presentation/Presenters/ContextMenus/ParameterIdentificationContextMenuItems.cs:91]: Yeah, it's always been that way. Unless you override that behavior like we do for folders and modules where they expand the node.
