### PR TITLE
Fixes #466 base grid comma

### LINKED ISSUE #466: Entering a basegrid value using comma leads to a wrong message in some cases

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/OSPSuite.Presentation/Presenters/ObservedData/DataRepositoryDataPresenter.cs [hunk 1]
```diff
@@ -90,9 +90,7 @@ public void AddData(int rowIndex)
       /// <returns></returns>
       public IEnumerable<string> GetCellValidationErrorMessages(int rowIndex, int columnIndex, string newValue)
       {
-         if (!float.TryParse(newValue, out var proposedValue))
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/ObservedData/DataRepositoryDataPresenter.cs]: This is not required because the method throws an exception of the value is not a float. 
Moreover, this cannot happen because we have a formatting in place

File: tests/OSPSuite.Core.Tests/Presentation/DataRepositoryDataPresenterSpecs.cs [hunk 2]
```diff
@@ -145,23 +145,6 @@ public void should_not_return_validation_messages()
...
    }
 
-   public class When_getting_validation_messages_for_invalid_value : concern_for_DataRepositoryDataPresenter
-   {
-      private List<string> _result;
-
-      protected override void Because()
-      {
-         sut.EditObservedData(_dataRepository);
-         _result = sut.GetCellValidationErrorMessages(0, 0, "blah").ToList();
```
Comment (msevestre) [inline tests/OSPSuite.Core.Tests/Presentation/DataRepositoryDataPresenterSpecs.cs]: Cannot happen anymore
