### PR TITLE
Fixes #357 side margine emable won't work

### LINKED ISSUE #357: Side Margins Enabled will not work if unchecked in Parameter Identification
see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/562

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs [hunk 1]
```diff
@@ -26,8 +26,7 @@ namespace OSPSuite.Presentation.Presenters.Charts
    ///    - ChartOptions for editing properties of chartSettings.
    /// </summary>
    public interface IChartEditorPresenter : IPresenter<IChartEditorView>,
-      IListener<ChartUpdatedEvent>,
-      IListener<ChartPropertiesChangedEvent>
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs]: This is not required in this component. The event is only raise from this presenter so we can call the handle directly

File: src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs [hunk 2]
```diff
@@ -230,7 +229,7 @@ public class ChartEditorPresenter : AbstractCommandCollectorPresenter<IChartEdit
          _dataBrowserPresenter.SelectionChanged += (o, e) => onSelectionChanged(e.Columns);
 
          _chartExportSettingsPresenter.ChartExportSettingsChanged += (o,e)=> onChartPropertiesChanged();
-         _chartSettingsPresenter.ChartSettingsChanged += (o, e) => onChartPropertiesChanged();
+         _chartSettingsPresenter.ChartSettingsChanged += (o, e) => updateChart();
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs]: Need to call full update when settings are changing (full update redraws everything). Indeed, sideMarginEnabled updates axis and not only chart

File: src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs [hunk 3]
```diff
@@ -281,6 +280,7 @@ private void updateChart()
       private void onChartPropertiesChanged()
       {
          _eventPublisher.PublishEvent(new ChartPropertiesChangedEvent(Chart));
+         ChartChanged();
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs]: calling chartchanged directly
