### PR TITLE
Fixes #2320

### LINKED ISSUE #2320: Create a cancel exception and handle cancelation of commands
relates to https://github.com/Open-Systems-Pharmacology/MoBi/issues/1411

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #2320 Create a cancel exception and handle cancelation of commands

## Type of change

Please mark relevant options with an `x` in the brackets.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/OSPSuite.Presentation/Services/ExceptionManager.cs [hunk 1]
```diff
@@ -27,7 +28,11 @@ public ExceptionManager(IDialogCreator dialogCreator, IExceptionView exceptionVi
 
       public override void LogException(Exception ex)
       {
-         if (ex.IsInfoException())
+         if (ex is CancelCommandRunException)
+         {
+            // empty clause here because we simply are unwinding the call stack
```
Comment (rwmcintosh) [inline src/OSPSuite.Presentation/Services/ExceptionManager.cs:33]: the plan is to throw exceptions when users decline to convert their pk-sim modules to extension modules. We are just going to unwind the stack when they choose to cancel. That prevents other commands from running if they are in a sequence

**Review by Yuri05 — APPROVED** [review]
