### PR TITLE
2720 link data to simulations wrong behavior

### LINKED ISSUE #2720: "Link data to simulations" wrong behavior
[Alfentanil_linkingDataBug.zip](https://github.com/user-attachments/files/24172398/Alfentanil_linkingDataBug.zip)

In the attached project, open the simulation `Ferrier 1985, Alfentanil iv 0.05 mg/kg`. All the observed data are mapped to the same output:

Image

And all data are present in the plot:

Image

In the first plot, select "Link Data to Simulations"

Image

- The colors in the "Curbe ad Axis Settings" are updated, but not in the plot. **Bug 1.** After closing the simulation and reopening, correct coloring is applied:

Image

Then, add any additional output in the simulatoin (using the "Defined Settings and Run" and assign some observed data to the new output:

Image

Click "Link data to simulations" again and add the new output. All data still have the same color as the first curve, but the data sets that are mapped to the second output should have the color blue!

Image

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #2720

# Description

When adding a second observed data, the curves should be drawn on a different color.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
image

# Questions (if appropriate):

### CODE REVIEW

**Review by Yuri05 — APPROVED** [review]

File: src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs [hunk 1]
```diff
@@ -675,25 +678,21 @@ public void AddCurvesWithSameColorForColumn(IReadOnlyList<DataColumn> dataColumn
...
       public Curve AddCurveForColumn(DataColumn dataColumn, CurveOptions defaultCurveOptions = null, bool isLinkedDataToSimulation = false)
       {
-         var (exists, curve) = createAndConfigureCurve(dataColumn, defaultCurveOptions);
-
-         if (exists)
-         {
-            if (isLinkedDataToSimulation)
-               Chart.UpdateCurveColorAndStyle(curve, dataColumn, AllDataColumns, isLinkedDataToSimulation: true);
-            return curve;
-         }
```
Comment (rwmcintosh) [inline src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs:685]: Causes a regression

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2752
