### PR TITLE
1056 unit not updating fixed

### LINKED ISSUE #1056: unit does not get updated after change
In the importer the unit cannot be set or validated anymore

### PR DESCRIPTION
**Pull request by georgeDaskalakis**
fixes #1056

### CODE REVIEW

File: src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs [hunk 1]
```diff
@@ -145,44 +144,45 @@ public void SetDescriptionForRow(ColumnMappingDTO model)
...
-
-         var metaData = _currentModel.Source as MetaDataFormatParameter;
-         if (metaData == null) return;
+         if (mappingSource == null)
+            return;
 
-         _mappings.First(m => m.MappingName == metaData.MetaDataId).ExcelColumn = _metaDataParameterEditorPresenter.Input;
-         metaData.ColumnName = _metaDataParameterEditorPresenter.Input;
-         metaData.IsColumn = false;
+         _mappings.First(m => m.MappingName == mappingSource.MetaDataId).ExcelColumn = _metaDataParameterEditorPresenter.Input;
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs:152]: First will throw an exception if not found...Or it cannot happen in this scenario?

File: src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs [hunk 2]
```diff
@@ -145,44 +144,45 @@ public void SetDescriptionForRow(ColumnMappingDTO model)
...
+         var model = _mappings.FirstOrDefault(x => x.Source == mappingSource);
+
+         if (model == null) 
+            return;
+
+         var column = ((MappingDataFormatParameter)model.Source).MappedColumn;
          column.Unit = _mappingParameterEditorPresenter.Unit;
          if (!string.IsNullOrEmpty(column.Unit.ColumnName))
          {
             column.Unit = new UnitDescription(_rawData.GetColumn(column.Unit.ColumnName).First(u => !string.IsNullOrEmpty(u)), column.Unit.ColumnName);
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs:174]: same question here with the First (I know it's not from this code change but since I see it :))

File: src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs [hunk 3]
```diff
@@ -211,13 +211,7 @@ public void UpdateDescriptrionForModel()
...
       {
          var metaDataCategory = _metaDataCategories.FindByName(model.MappingName);
-         if (metaDataCategory != null && metaDataCategory.AllowsManualInput)
-         {
-            _currentModel = model;
-            return true;
-         }
-
-         return false;
+         return metaDataCategory != null && metaDataCategory.AllowsManualInput;
```
Comment (msevestre) [inline src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs:214]: much better. No side effect

**Review by msevestre — COMMENTED** [review]
a question regarding First

File: src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs (hunk 1 above)
Comment (georgeDaskalakis) [reply src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs:152]: Well in that case it would mean that we changed the unit for a mapping that doesn't exist - which would really be a software bug. I would let the exception be raised i this quite improbable case.

File: src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs (hunk 2 above)
Comment (georgeDaskalakis) [reply src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs:174]: same answer here: not found would mean we mapped a column that did not exist, I suggest we keeo the same behaviour as above.

**Comment by msevestre** [comment]
ok merging then. I think next time, it would be good to add comments explaining why we want to use First.
