### PR TITLE
Fixes #2300 Importing with column unit mapping

### LINKED ISSUE #2300: Importing with column unit mapping
When you import data with units described in a column, it should be possible to select the dimension.

For example, when importing mass in mg the importer will select the wrong dimension since input dose contains the mg unit, and is alphabetically first.

image

image

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #2300

# Description
If users try to map a dimension from a column that contains units then this has a couple of improvements

1. Formerly, only the first unit was used to determine the dimension, now we use all the units from the column
2. If there was more than one dimension supporting the units of the column then the first in the list would be selected (that list was always alaphabetic in the importer.

What this PR does - if there is an ambiguous unit->dimension mapping in the dataset then we present a modal dialog and the user must select the dimension for the column. There is also an 'Apply to All' button for each row so that if there are several columns in the data with the same dimensions you can override them all.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):
See this data (there are two sheets):
image

Adding the sheets
image

Since both sheets have the same 'possible dimensions' using the apply to all maps both
image

# Questions (if appropriate):

### CODE REVIEW

**Comment by PavelBal** [comment]
But what happens if you have multiple data sets with different dimension from the same sheet?

**Comment by rwmcintosh** [comment]
> But what happens if you have multiple data sets with different dimension from the same sheet?

I thought of that, but not hard enough. You can't tell the 'Group' difference.
image


I'll add it

**Comment by rwmcintosh** [comment]
image

File: src/OSPSuite.Presentation/DTO/DimensionSelectionDTO.cs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+      public string DisplayName
+      {
+         get
+         {
+            if (string.IsNullOrEmpty(_description))
+               return $"{_sheetName} - {Column.Name}";
+            return $"{_sheetName} - {Column.Name} - {_description}";
+         }
+      }
+   }
```
Comment (Yuri05) [inline src/OSPSuite.Presentation/DTO/DimensionSelectionDTO.cs:38]: for CSV files, sheet name will be empty. I assume the name should be then just `{Column.Name} - {_description}`

Comment (rwmcintosh) [reply src/OSPSuite.Presentation/DTO/DimensionSelectionDTO.cs]: Yes, I refactored it now to deal with csv files better

**Review by Yuri05 — APPROVED** [review]
